# Builds go binary
FROM golang:1.18 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

# Copys source code into the container
COPY . /service

# Builds service binary
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Buils service in alpine
FROM alpine:3.14
ARG BUILD_REF
ARG BUILD_DATE
COPY --from=build_sales-api /service /service/service
WORKDIR /service
CMD ["./service"]

# Metadata
LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="Jake Sixsmith <jcsix694>" \
      org.opencontainers.image.source="https://github.com/jcsix694/service3-video" \
      org.opencontainers.image.revision="${BUILD_REF}}" \
      org.opencontainers.image.vendor="Jake" \